pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merge for Dependabot-preview pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
        strict: true
