dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: edgedalmacio-github
    token:
      secure: akSMG1B1DI0NwVcimPM7K19C/DLtbwgJqaJfnlaA1axZ0xnCXZqATZFOYpY6GeRtiHhqSEewqjVyMjIEccJ6K2HRqVmFume9v84WsGJRwAYTZR0pjNUGuNkRlW3i9lK2sYG7TzG1iagHd29RnDO4m4OcE54Mf700RB3voPEAwII=
jdk:
  - oraclejdk8
env:
  matrix:
    secure: EokAWva6gfwYCz+ljHPC1m+zrqmgtTmmym/o+QwUm7xPjJtPl1fHQyxQFPWPrnOVKGVV+9AVPY3O3UHdhyEiuvA6Pjkb6RB0Zi7vaqPyGsyxdiDiYVzkiTwdvrMWNofK/Kmdio+RVuYXb5AVQmKAAwabau+A4ZrLZhFb72ed7E4=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
